//
// Created by riedel on 2/11/20.
//

#ifndef INC_7542_VERIFICADOR_EBPF_PILAPROTEGIDA_H
#define INC_7542_VERIFICADOR_EBPF_PILAPROTEGIDA_H


class PilaProtegida {

};


#endif //INC_7542_VERIFICADOR_EBPF_PILAPROTEGIDA_H
